development:
  adapter: mysql2
  database: fitness_dev
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: fitness_test
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: fitness_production
  host: venuto-1.ckvalclmta0k.us-west-2.rds.amazonaws.com:3306
  port: 3306
  username: NuihKg3
  password: 9vyE49nf43hQMMGk
  pool: 5
  timeout: 5000
